// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Reactor.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_REACTOR_H_
#define _FAST_DDS_GENERATED_REACTOR_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(REACTOR_SOURCE)
#define REACTOR_DllAPI __declspec( dllexport )
#else
#define REACTOR_DllAPI __declspec( dllimport )
#endif // REACTOR_SOURCE
#else
#define REACTOR_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define REACTOR_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;

} // namespace fastcdr
} // namespace eprosima



/*!
 * @brief This class represents the structure reactor_progress defined by the user in the IDL file.
 * @ingroup Reactor
 */
class reactor_progress
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport reactor_progress();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~reactor_progress();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object reactor_progress that will be copied.
     */
    eProsima_user_DllExport reactor_progress(
            const reactor_progress& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object reactor_progress that will be copied.
     */
    eProsima_user_DllExport reactor_progress(
            reactor_progress&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object reactor_progress that will be copied.
     */
    eProsima_user_DllExport reactor_progress& operator =(
            const reactor_progress& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object reactor_progress that will be copied.
     */
    eProsima_user_DllExport reactor_progress& operator =(
            reactor_progress&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x reactor_progress object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const reactor_progress& x) const;

    /*!
     * @brief Comparison operator.
     * @param x reactor_progress object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const reactor_progress& x) const;

    /*!
     * @brief This function sets a value in member progress
     * @param _progress New value for member progress
     */
    eProsima_user_DllExport void progress(
            int32_t _progress);

    /*!
     * @brief This function returns the value of member progress
     * @return Value of member progress
     */
    eProsima_user_DllExport int32_t progress() const;

    /*!
     * @brief This function returns a reference to member progress
     * @return Reference to member progress
     */
    eProsima_user_DllExport int32_t& progress();


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::vector<uint8_t>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::vector<uint8_t>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::vector<uint8_t>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::vector<uint8_t>& data();

private:

    int32_t m_progress{0};
    std::vector<uint8_t> m_data;

};
/*!
 * @brief This class represents the structure reactor_void_progress defined by the user in the IDL file.
 * @ingroup Reactor
 */
class reactor_void_progress
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport reactor_void_progress();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~reactor_void_progress();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object reactor_void_progress that will be copied.
     */
    eProsima_user_DllExport reactor_void_progress(
            const reactor_void_progress& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object reactor_void_progress that will be copied.
     */
    eProsima_user_DllExport reactor_void_progress(
            reactor_void_progress&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object reactor_void_progress that will be copied.
     */
    eProsima_user_DllExport reactor_void_progress& operator =(
            const reactor_void_progress& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object reactor_void_progress that will be copied.
     */
    eProsima_user_DllExport reactor_void_progress& operator =(
            reactor_void_progress&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x reactor_void_progress object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const reactor_void_progress& x) const;

    /*!
     * @brief Comparison operator.
     * @param x reactor_void_progress object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const reactor_void_progress& x) const;

    /*!
     * @brief This function sets a value in member dummy
     * @param _dummy New value for member dummy
     */
    eProsima_user_DllExport void dummy(
            int32_t _dummy);

    /*!
     * @brief This function returns the value of member dummy
     * @return Value of member dummy
     */
    eProsima_user_DllExport int32_t dummy() const;

    /*!
     * @brief This function returns a reference to member dummy
     * @return Reference to member dummy
     */
    eProsima_user_DllExport int32_t& dummy();

private:

    int32_t m_dummy{0};

};
/*!
 * @brief This class represents the enumeration Command defined by the user in the IDL file.
 * @ingroup Reactor
 */
enum Command : uint32_t
{
    CANCEL
};
/*!
 * @brief This class represents the structure reactor_command defined by the user in the IDL file.
 * @ingroup Reactor
 */
class reactor_command
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport reactor_command();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~reactor_command();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object reactor_command that will be copied.
     */
    eProsima_user_DllExport reactor_command(
            const reactor_command& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object reactor_command that will be copied.
     */
    eProsima_user_DllExport reactor_command(
            reactor_command&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object reactor_command that will be copied.
     */
    eProsima_user_DllExport reactor_command& operator =(
            const reactor_command& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object reactor_command that will be copied.
     */
    eProsima_user_DllExport reactor_command& operator =(
            reactor_command&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x reactor_command object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const reactor_command& x) const;

    /*!
     * @brief Comparison operator.
     * @param x reactor_command object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const reactor_command& x) const;

    /*!
     * @brief This function sets a value in member command
     * @param _command New value for member command
     */
    eProsima_user_DllExport void command(
            Command _command);

    /*!
     * @brief This function returns the value of member command
     * @return Value of member command
     */
    eProsima_user_DllExport Command command() const;

    /*!
     * @brief This function returns a reference to member command
     * @return Reference to member command
     */
    eProsima_user_DllExport Command& command();

private:

    Command m_command{::CANCEL};

};


#include "ReactorCdrAux.hpp"

#endif // _FAST_DDS_GENERATED_REACTOR_H_

