#ifndef reactor_idl
#define reactor_idl

struct reactor_progress
{
    @key int32 progress;
    sequence<octet> data;
};

// Standin type if no progress data
struct reactor_void_progress
{
    int32 dummy;
};

enum Command
{
    CANCEL
};

struct reactor_command
{
    Command command;
};

#endif

 
